export interface MemoizedFunction<T extends (...args: never[]) => unknown> {
    (...args: Parameters<T>): ReturnType<T>;
    /** Clears the cache. */
    clear: () => void;
    /** Removes the entry for these arguments, returning whether it existed. */
    delete: (...args: Parameters<T>) => boolean;
    /** Caches a value for these arguments, starting a fresh TTL. */
    set: (value: ReturnType<T>, ...args: Parameters<T>) => void;
}

/**
 * Memoizes a function by caching its results based on the input arguments.
 * A resolver function can be provided to customize the key generation.
 * If no resolver is provided, the key will be generated by JSON stringify-ing the input arguments.
 * Rejected promises are evicted. Expired entries are swept lazily on calls and writes,
 * at most once per maxAge interval; no cleanup timers are created.
 * @param fn The function to memoize
 * @param options Optional key resolver and cache lifetime in milliseconds
 * @example
 * // 1. Basic usage
 * const heavyCalc = memoize((n: number) => {
 *     console.log('Calculating...');
 *     return n * 2;
 * });
 * heavyCalc(5); // Logs 'Calculating...' and returns 10
 * heavyCalc(5); // Returns 10 immediately from cache
 * @example
 * // 2. Using maxAge (TTL)
 * const getStockPrice = memoize(fetchPrice, { maxAge: 60000 }); // 1 minute cache
 * @example
 * // 3. Using a custom resolver
 * const getUser = memoize(
 *     (user, theme) => render(user, theme),
 *     { resolver: (user) => user.id } // Only cache based on ID, ignore theme
 * );
 * @example
 * // 4. Manual cache clearing
 * heavyCalc.clear();
 * @example
 * // 5. Seed or invalidate one entry using the original arguments
 * const getFlag = memoize(async (id: string) => readFlag(id));
 * await writeFlag("drops", true);
 * getFlag.set(Promise.resolve(true), "drops");
 * getFlag.delete("drops");
 */
export function memoize<T extends (...args: never[]) => unknown>(
    fn: T,
    options: {
        /** Function to generate a cache key from the input arguments. */
        resolver?: (...args: Parameters<T>) => string;
        /** The time to wait in milliseconds before expiring a cache entry. */
        maxAge?: number;
    } = {}
): MemoizedFunction<T> {
    const cache = new Map<string, { value: ReturnType<T>; timestamp: number }>();
    const { resolver, maxAge } = options;
    let lastSweep = Date.now();

    const getKey = (...args: Parameters<T>) => (resolver ? resolver(...args) : JSON.stringify(args));

    const sweep = (now: number) => {
        if (!maxAge || now - lastSweep < maxAge) return;
        lastSweep = now;

        for (const [key, entry] of cache) {
            if (now - entry.timestamp >= maxAge) cache.delete(key);
        }
    };

    const cacheValue = (key: string, value: ReturnType<T>, timestamp: number) => {
        const entry = { value, timestamp };
        cache.set(key, entry);

        if (
            value !== null &&
            (typeof value === "object" || typeof value === "function") &&
            "then" in value &&
            typeof value.then === "function"
        ) {
            // Observe rejection without replacing the caller's promise or rejecting the observer.
            void Promise.resolve(value).catch(() => {
                // An older pending result must not evict a replacement for the same key.
                if (cache.get(key) === entry) cache.delete(key);
            });
        }
    };

    const memoized = function (this: unknown, ...args: Parameters<T>) {
        const key = getKey(...args);
        const now = Date.now();
        sweep(now);
        const entry = cache.get(key);

        if (entry) {
            if (!maxAge || now - entry.timestamp < maxAge) {
                return entry.value;
            }
            cache.delete(key);
        }

        const result = (fn as (...args: Parameters<T>) => ReturnType<T>).apply(this, args);
        cacheValue(key, result, now);
        return result;
    } as MemoizedFunction<T>;

    memoized.clear = () => cache.clear();
    memoized.delete = (...args) => cache.delete(getKey(...args));
    memoized.set = (value, ...args) => {
        const key = getKey(...args);
        const now = Date.now();
        sweep(now);
        cacheValue(key, value, now);
    };

    return memoized;
}
